parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver:         'pdo_mysql'
        charset:        'utf8'

        types:
            json: Sonata\Doctrine\Types\JsonType
            datetime: ASM\Doctrine\DBAL\Types\DateTimeUTCType
            datetimeutc: ASM\Doctrine\DBAL\Types\DateTimeUTCType

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'Shapecode\Devliver\Entity'
                alias: App
        resolve_target_entities:
            Tenolo\Bundle\UserBundle\Entity\Plan\UserInterface: Shapecode\Devliver\Entity\User
            Symfony\Component\Security\Core\User\UserInterface: Shapecode\Devliver\Entity\User
            FOS\UserBundle\Model\UserInterface: Shapecode\Devliver\Entity\User
            Sonata\UserBundle\Model\UserInterface: Shapecode\Devliver\Entity\User
