parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver:         'pdo_mysql'
        charset:        'utf8mb4'

        host:           '%database_host%'
        port:           '%database_port%'
        dbname:         '%database_name%'
        user:           '%database_user%'
        password:       '%database_password%'

        types:
            json: Sonata\Doctrine\Types\JsonType

        # With Symfony 3.3, remove the `resolve:` prefix
#        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
