fos_user:
    db_driver: orm
    user_class: Shapecode\Devliver\Entity\User
    firewall_name: main

    from_email:
        address:        "%mailer_user%"
        sender_name:    "%mailer_user%"

    group:
        group_class: Shapecode\Devliver\Entity\UserGroup
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager

    resetting:
        retry_ttl: 0