framework:
    #esi: ~
    default_locale: '%locale%'
    translator:
        fallbacks: ['en']
    secret: '%env(APP_SECRET)%'
    router:
        strict_requirements: ~
    form: ~
    templating:
        engines: ['twig']
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    trusted_hosts: ~
    session:
        handler_id: ~
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    cache:
        prefix_seed: shapecode/devliver
