sonata_user:
    security_acl: false
    manager_type: orm

    class:
        user: Shapecode\Devliver\Entity\User
        group: Shapecode\Devliver\Entity\UserGroup

    admin:
        user:
            class: Shapecode\Devliver\Admin\UserAdmin