swiftmailer:
    transport:        "%mailer_transport%"
    host:             "%mailer_host%"
    username:         "%mailer_user%"
    password:         "%mailer_password%"
    port:             "%mailer_port%"
    encryption:       "%mailer_encryption%"
    auth_mode:        "%mailer_auth_mode%"
    sender_address:   "%mailer_user%"
    spool: { type: 'memory' }
