services:

    devliver.admin.package:
        class: Shapecode\Devliver\Admin\PackageAdmin
        arguments: [~, Shapecode\Devliver\Entity\Package, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Packages, group: Packages }
        public: true
