parameters:
    devliver_dir:           '%kernel.project_dir%/var/devliver'
    version_file:           '%kernel.project_dir%/version'

    devliver_package_dir:   '%devliver_dir%/package'
    devliver_dist_dir:      '%devliver_dir%/dist'
    devliver_composer_dir:  '%devliver_dir%/composer'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $composerDirectory: '%devliver_composer_dir%'
            $distDir: '%devliver_dist_dir%'
            $versionFile: '%version_file%'
            $projectDir: '%kernel.project_dir%'
            Symfony\Component\Cache\Adapter\TagAwareAdapterInterface: '@cache.tag.app'

    _instanceof:
        Doctrine\Common\EventSubscriber:
            tags: ['doctrine.event_subscriber']

    Cocur\Slugify\Slugify: ~

    cache.tag.app:
        class: Symfony\Component\Cache\Adapter\TagAwareAdapter
        decorates: cache.app
        arguments: ['@cache.tag.app.inner']

    # controller
    Shapecode\Devliver\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']

    # composer
    Shapecode\Devliver\Composer\:
        resource: '../../Composer/*'

    # event listener
    Shapecode\Devliver\EventListener\:
        resource: '../../EventListener/*'

    # twig
    Shapecode\Devliver\Twig\:
        resource: '../../Twig/*'

    # service
    Shapecode\Devliver\Service\:
        resource: '../../Service/*'

    # command
    Shapecode\Devliver\Command\:
        resource: '../../Command/*'

    # form
    Shapecode\Devliver\Form\:
        resource: '../../Form/*'

    # menu
    Shapecode\Devliver\Menu\Builder: ~

    devliver.main_menu_left:
        class: Knp\Menu\MenuItem
        factory: ['@Shapecode\Devliver\Menu\Builder', mainMenu]
        tags:
            - { name: knp_menu.menu, alias: main_left }

    devliver.main_menu_right:
        class: Knp\Menu\MenuItem
        factory: ['@Shapecode\Devliver\Menu\Builder', rightNavbar]
        tags:
            - { name: knp_menu.menu, alias: main_right }

    # security
    Shapecode\Devliver\Security\:
        resource: '../../Security/*'

    devliver.security.token_authenticator: '@Shapecode\Devliver\Security\TokenAuthenticator'
    devliver.security.api_token_user_provider: '@Shapecode\Devliver\Security\ApiTokenUserProvider'
    devliver.security.repository_token_user_provider: '@Shapecode\Devliver\Security\RepositoryTokenUserProvider'

    # admin
    Shapecode\Devliver\Admin\PackageAdmin:
        arguments: [~, Shapecode\Devliver\Entity\Package, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Packages, group: Packages }
