parameters:
    devliver_dir:           '%kernel.project_dir%/var/devliver'
    version_file:           '%kernel.project_dir%/version'

    devliver_package_dir:   '%devliver_dir%/package'
    devliver_dist_dir:      '%devliver_dir%/dist'
    devliver_composer_dir:  '%devliver_dir%/composer'

services:

    cache.tag.app:
        class: Symfony\Component\Cache\Adapter\TagAwareAdapter
        decorates: cache.app
        arguments: ['@cache.tag.app.inner']

    # synchronization
    devliver.package_synchronization:
        class: Shapecode\Devliver\Service\PackageSynchronization
        public: true
        arguments:
            - '@doctrine'
            - '@devliver.composer_manager'
            - '@devliver.repository_helper'

    devliver.dist_synchronization:
        class: Shapecode\Devliver\Service\DistSynchronization
        public: true
        arguments:
            - '@devliver.composer_manager'
            - '%devliver_dist_dir%'

    # composer
    devliver.config_factory:
        class: Shapecode\Devliver\Composer\ConfigFactory
        public: false
        arguments:
            - '%devliver_composer_dir%'
            - '%kernel.project_dir%'

    devliver.composer_manager:
        class: Shapecode\Devliver\Composer\ComposerManager
        public: true
        arguments:
            - '@doctrine'
            - '@devliver.config_factory'

    # event listener
    devliver.event_listener.entity:
        class: Shapecode\Devliver\EventListener\EntityListener
        tags:
            - { name: doctrine.event_subscriber }

    devliver.event_listener.fos_user:
        class: Shapecode\Devliver\EventListener\FosUserListener
        arguments:
            - '@router'
        tags:
            - { name: kernel.event_subscriber }

    devliver.event_listener.package_access:
        class: Shapecode\Devliver\EventListener\PackageAccessListener
        arguments:
            - '@cache.app'
        tags:
            - { name: doctrine.event_subscriber }

    devliver.event_listener.package:
        class: Shapecode\Devliver\EventListener\PackageListener
        arguments:
            - '@cache.app'
        tags:
            - { name: doctrine.event_subscriber }

    devliver.event_listener.user:
        class: Shapecode\Devliver\EventListener\UserListener
        tags:
            - { name: doctrine.event_subscriber }

    # twig
    devliver.twig_extension.devliver:
        class: Shapecode\Devliver\Twig\Extension\DevliverExtension
        arguments:
            - '@doctrine'
            - '@router'
            - '@devliver.github_release'
            - '@devliver.composer_manager'
            - '@devliver.repository_helper'
        tags:
            - { name: twig.extension }

    # service
    devliver.github_release:
        class: Shapecode\Devliver\Service\GitHubRelease
        arguments:
            - '@Github\Client'
            - '@cache.app'
            - '%version_file%'

    devliver.packages_dumper:
        class: Shapecode\Devliver\Service\PackagesDumper
        public: true
        arguments:
            - '@doctrine'
            - '@router'
            - '@devliver.repository_helper'
            - '@cache.app'

    devliver.repository_helper:
        class: Shapecode\Devliver\Service\RepositoryHelper
        public: true
        arguments:
            - '@demontpx_parsedown.parsedown'
            - '@router'

    # command
    devliver.console_command.migrate:
        class: Shapecode\Devliver\Command\MigrateCommand
        tags:
            - { name: console.command }

    devliver.console_command.packages_update:
        class: Shapecode\Devliver\Command\PackagesUpdateCommand
        arguments:
            - '@devliver.package_synchronization'
        tags:
            - { name: console.command }

    devliver.console_command.self_update:
        class: Shapecode\Devliver\Command\SelfUpdateCommand
        arguments:
            - '@devliver.github_release'
            - '@kernel'
        tags:
            - { name: console.command }

    # menu
    devliver.menu_builder:
        class: Shapecode\Devliver\Menu\Builder
        arguments:
            - "@translator"
            - "@knp_menu.factory"
            - "@security.authorization_checker"
            - "@security.token_storage"

    devliver.main_menu_left:
        class: Knp\Menu\MenuItem
        factory: ["@devliver.menu_builder", mainMenu]
        tags:
            - { name: knp_menu.menu, alias: main_left }

    devliver.main_menu_right:
        class: Knp\Menu\MenuItem
        factory: ["@devliver.menu_builder", rightNavbar]
        tags:
            - { name: knp_menu.menu, alias: main_right }

    # form
    devliver.form_validator.package:
        class: Shapecode\Devliver\Form\Validator\PackageValidator
        public: true
        arguments:
            - '@devliver.composer_manager'
            - '@devliver.repository_helper'
            - '@doctrine'
